---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-app
  namespace: ${ENVIRONMENT}
  labels:
    app: car-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-app
  template:
    metadata:
      labels:
        app: car-app
    spec:
      containers:
      - name: car-app
        image: nanotkarashish/car_app:latest
        ports:
        - containerPort: 8080
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        ports:
        - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: car-app
  name: car-app
  namespace: ${ENVIRONMENT}
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    app: car-app

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: car-app
  namespace: ${ENVIRONMENT}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: car-app.${ENVIRONMENT}.local
    http:
      paths:
      - path: /
        backend:
          serviceName: car-app
          servicePort: 8080
