#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: devel

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: car-app
  name: car-app
  namespace: devel
spec:
  containers:
  - name: car-app
    image: nanotkarashish/car_app:latest
    ports:
      - containerPort: 8080
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    ports:
      - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: car-app
  name: car-app
  namespace: devel
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    app: car-app

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: car-app
  namespace: devel
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: car-app.devel.local
    http:
      paths:
      - path: /
        backend:
          serviceName: car-app
          servicePort: 8080
